добавила новую страницу item_card (html+css)
Altynay18/Kolesa-Upgrade-FE-2021 pull request #2
Opened 2021-09-25 21:10 UTC by Altynay18

2021-09-26 06:51 UTC, BekStar7 commented
Не сделано пункты:
- `Отцентровано на странице по вертикали и горизонтали`. Именно не сделано по вертикали
- Высота у тебя фиксированная
- `Ширина фиксированная, но может меняться если отстуствет блок с фото.` - не сделано этот пункт, это когда Я удаляю фотку
- Обязаталеьные блоки: Заголовок товара, стоимость товара, кнопка действия, блок “твой баланс”. Всех остальных элементов может не быть, **нужно это предусмотреть чтобы верстка не взорвалась.** - верстка не верен, скриншоты будет
- Предусмотреть правильную многострочность. - не сделано
- `Добавить класс для “активной” превьюшки.` не сделано
-  `Количество опций может быть любым. Предусмотреть правильную многострочность.` - не сделано
- (*) Реализовать функционал переключения опций через radio-buttons

2021-09-26 06:52 UTC, BekStar7 commented
<img width="1322" alt="Снимок экрана 2021-09-26 в 10 32 41" src="https://user-images.githubusercontent.com/29562716/134797003-848742f2-1638-43a2-81b3-85beee2530c4.png">
<img width="479" alt="Снимок экрана 2021-09-26 в 10 35 21" src="https://user-images.githubusercontent.com/29562716/134797005-d5963ab8-ff42-4e13-ace7-46aea4c71e23.png">
<img width="760" alt="Снимок экрана 2021-09-26 в 10 50 38" src="https://user-images.githubusercontent.com/29562716/134797007-806929f5-e9cc-4dcb-a9d4-8af252e4bd94.png">

2021-09-26 07:04 UTC, BekStar7 reviewed
html файлы всегда прогоняй автоматический форматирование - html beatify, чтобы было правильное табуляций и без лишных строк

2021-09-26 07:04 UTC, BekStar7 commented on .vscode/launch.json
> +    // Используйте IntelliSense, чтобы узнать о возможных атрибутах.
По идее это не должно попадать в git коммит =) Можно добавить в gitignore `.vscode`
#не_критично
(Не критично - означает, что на оценку не влияет, но для оучшего кода можно сделать, на свое усмотрение)

2021-09-26 07:04 UTC, BekStar7 commented on src/js/main.js
>  document.querySelector('#app').innerHTML = `
Можно было этот код удалить оставив, import css

2021-09-26 07:04 UTC, BekStar7 commented on item_card.html
> +                <div class="model"><img src="src/assets/model1.png"></div>
нету активного класса

2021-09-26 07:04 UTC, BekStar7 commented on item_card.html
> +                <div class="item_name">
По мне лишний div

2021-09-26 07:04 UTC, BekStar7 commented on item_card.html
> +                <div class="price">
Лишний можно просто h3 оставить

2021-09-26 07:04 UTC, BekStar7 commented on item_card.html
> +                    <h3>Футболка "Эволюционируй или сдохни"</h3>
Как принято по семантическйо html - лучше начинать h2

2021-09-26 07:04 UTC, BekStar7 commented on item_card.html
> +                    <div class="bag">
лишний div

2021-09-26 07:04 UTC, BekStar7 commented on item_card.html
> +            <button class="button" type="button">Заказать</button> <!-- double check here-->
<!-- double check here--> не нуженый коммент

2021-09-26 07:04 UTC, BekStar7 commented on item_card.html
> +                    <h5 class="item_details_color">Цвета:</h5>
не правильный табуляций и почему h5 ? =) Достаточно h3 или p

2021-09-26 07:04 UTC, BekStar7 commented on item_card.html
> +                <div><img src="model"><img src="src/assets/model2.png"></div>
Не нужен этот `<img src="model">`, удали его

2021-09-26 07:04 UTC, BekStar7 commented on item_card.html
> +                    <div class="color_option" style="background-color: #d6ecfb;">
Не нужен Inline-style, стили пишем в css,

2021-09-26 07:04 UTC, BekStar7 commented on item_card.html
> +                            <h5>Синий</h5>
это `p` или`span`, а не `h5`

2021-09-26 07:04 UTC, BekStar7 commented on item_card.html
> +                            <h5>Бежевый</h5>
то же самое

2021-09-26 07:04 UTC, BekStar7 commented on item_card.html
> +                            <h5>Серый</h5>
тоже

2021-09-26 07:04 UTC, BekStar7 commented on item_card.html
> +                <h5 class="size_title">Размер:</h5>
h3 или p

2021-09-26 07:04 UTC, BekStar7 commented on item_card.html
> +                    <div class="size" style="background-color: #d6ecfb;">S</div>
Удали inline style

2021-09-26 07:04 UTC, BekStar7 commented on item_card.html
> +
Лишнее пустые строки

2021-09-26 07:23 UTC, BekStar7 commented
Не нужные backgorund png

2021-09-26 07:25 UTC, BekStar7 commented
По той причине, что прошлый PR не замержила, Я замержил 1-ю PR и создал конфликт, это тоже надо решить =) Всегда мержите PR сами =)

2021-09-26 07:27 UTC, BekStar7 commented
Верстка по отступами не соответствует макету надо привести к виду макету

2021-09-26 07:27 UTC, BekStar7 requested changes

2021-09-26 07:27 UTC, BekStar7 commented on item_card.html
> +<!DOCTYPE html>
html файлы всегда прогоняй автоматический форматирование - html beatify, чтобы было правильное табуляций и без лишных строк

2021-09-26 07:27 UTC, BekStar7 commented on item_card.html
> +                            <img src="src/assets/beige.png">
Можно без img обоитись, просто через `.the_color` делаешь `background`, и создаешь доп. классы, к примеру `the_color_red`, `the_color_blue`

2021-09-26 07:27 UTC, BekStar7 commented on src/css/item_card.css
> +    background-image: url(src/assets/body_background.png); /* revisit this part, why background_image is not working" */
Зачем тебе это картинка ? Не нужно

2021-09-26 07:27 UTC, BekStar7 commented on src/css/item_card.css
> +h5 {
Плохая практика стили делать на глобальные теги без класса, влияет на все тэги h5,  и перезаписать в других стилях и классах вызывает сложность

2021-09-26 07:27 UTC, BekStar7 commented on src/css/item_card.css
> +    top: 0;
Лишнее свойство по мне

2021-09-26 07:27 UTC, BekStar7 commented on item_card.html
> +    <div class="item_container">
Луше вообще назвать `modal-item` item не говорить о том что это модалка

2021-09-26 07:27 UTC, BekStar7 commented on src/css/item_card.css
> +    width: 1039px;
Из-за этого у тебя не будет сделан пункт когда при удаление фото меняется ширина

2021-09-26 07:27 UTC, BekStar7 commented on src/css/item_card.css
> +    height: 588px;
Ширина не должно быть фиксированным

2021-09-26 07:27 UTC, BekStar7 commented on src/css/item_card.css
> +    position: static;
не нужно писать `position: static;` он и так стоит

2021-09-26 07:27 UTC, BekStar7 commented on src/css/item_card.css
> +    height: 330px;
лучше так
```css
width: 330px;
height: auto;
```

2021-09-26 07:27 UTC, BekStar7 commented on src/css/item_card.css
> +    margin-top: 56px;
Внешнее padding на модалки делать в самом модалке, а не в самом дочерных элементах

2021-09-26 07:27 UTC, BekStar7 commented on src/css/item_card.css
> +    width: 653px;
не стоит фиксировать так ширину, пусть от контента все выставляется, можно написать min-width

2021-09-26 07:27 UTC, BekStar7 commented on src/css/item_card.css
> +    font-family: 'Open Sans', sans-serif;
font-family задаешь body, и больше не указываешь в каждом selector. По той причине шрифт наследуемое свойство

2021-09-26 07:27 UTC, BekStar7 commented on src/css/item_card.css
> +    width: 134px;
Пусть контент определяет ширину, так задавать не стоит

2021-09-27 06:40 UTC, Altynay18 commented
у меня не получилось вертикально оцентровать  modal-item, я пробовала 
 `  display: flex;
    flex-direction: column;
    justify-content: center;
    align-items: center;`
но не сработало. Мне кажется, что он конфликтит с какими-то свойствами. Можете, пожалуйста, посмотреть где ошибка?

2021-09-27 12:12 UTC, BekStar7 commented
Родителю задаешь размер  modal-item, height: 100vh

2021-09-28 03:31 UTC, BekStar7 approved these changes

2021-09-28 10:15 UTC, merged